import 'idioma.dart';

String texto(String clave) {
  if (Idioma.seleccionado == 'English') {
    return ingles[clave] ?? clave;
  }

  if (Idioma.seleccionado == 'Português') {
    return portugues[clave] ?? clave;
  }

  return espanol[clave] ?? clave;
}

final Map<String, String> espanol = {
  'haz_click_aqui': 'Haz click aquí!',
  'tu_proxima_gran_idea': 'Tu próxima gran idea comienza aquí!💫',
  'mensaje_inicio':
      'Crea tu cuenta en 30 segundos y descubre todo lo que tenemos para ti',
'comenzar': 'Comenzar ahora',
  'iniciar_sesion': 'Iniciar sesión',
  'iniciar_sesion_titulo': 'Iniciar Sesión',
  'crear_cuenta': 'Crear cuenta',
  'correo': 'Correo electrónico',
  'correo_electronico': 'Correo Electrónico',
  'contrasena': 'Contraseña',
  'confirmar_contrasena': 'Confirmar contraseña',
  'olvidaste_contrasena': '¿Olvidaste Contraseña?',
  'nombre': 'Nombre',
  'telefono': 'Teléfono',
  'recordarme': 'Recordarme',
  'no_tienes_cuenta': '¿No tienes cuenta? Regístrate',
  'continuar_con': 'O Continuar Con',
  'historial': 'Historial',
  'resenas': 'Reseñas',
  'menu': 'Menú',
  'perfil': 'Perfil',
  'mensajes': 'Mensajes',
  'cerrar_sesion': 'Cerrar sesión',
  'registro': 'Regístrate',
'crear_cuenta_boton': 'Crear Cuenta',
'error_contrasenas': 'Las contraseñas no coinciden',
'correo_registrado': 'Ese correo ya está registrado',
'error_servidor': 'No se pudo conectar con el servidor',
'verificando_correo': 'Verificando el Correo',
'ingresa_codigo': 'Ingresa el código de verificación',
'verificar_proceder': 'Verificar y Proceder',
'reenviar_codigo': 'Reenviar código',
'codigo_incorrecto': 'Código incorrecto',
'recuperar_contrasena': 'Recuperar Contraseña',
'no_se_pudo_enviar': 'No se pudo enviar el código',
'verificar_codigo_recuperacion': 'Verificar el código de recuperación',
'restaurar_contrasena': 'Restaurar Contraseña',
'escribir_nueva_contrasena': 'Escribir nueva contraseña',
'nueva_contrasena': 'Nueva contraseña',
'confirmar_nueva_contrasena': 'Confirmar nueva contraseña',
'continuar': 'Continuar',
};

final Map<String, String> ingles = {
  'haz_click_aqui': 'Click here!',
  'tu_proxima_gran_idea': 'Your next great idea starts here!💫',
  'mensaje_inicio':
      'Create your account in 30 seconds and discover everything we have for you',
'comenzar': 'Get started',
  'iniciar_sesion': 'Log in',
  'iniciar_sesion_titulo': 'Log In',
  'crear_cuenta': 'Create account',
  'correo': 'Email',
  'correo_electronico': 'Email',
  'contrasena': 'Password',
  'confirmar_contrasena': 'Confirm password',
  'olvidaste_contrasena': 'Forgot Password?',
  'nombre': 'Name',
  'telefono': 'Phone',
  'recordarme': 'Remember me',
  'no_tienes_cuenta': 'Don\'t have an account? Sign up',
  'continuar_con': 'Or Continue With',
  'historial': 'History',
  'resenas': 'Reviews',
  'menu': 'Menu',
  'perfil': 'Profile',
  'mensajes': 'Messages',
  'cerrar_sesion': 'Log out',
  'registro': 'Sign Up',
'crear_cuenta_boton': 'Create Account',
'error_contrasenas': 'Passwords do not match',
'correo_registrado': 'That email is already registered',
'error_servidor': 'Could not connect to the server',
'verificando_correo': 'Verifying Email',
'ingresa_codigo': 'Enter the verification code',
'verificar_proceder': 'Verify and Continue',
'reenviar_codigo': 'Resend code',
'codigo_incorrecto': 'Incorrect code',
'recuperar_contrasena': 'Recover Password',
'no_se_pudo_enviar': 'The code could not be sent',
'verificar_codigo_recuperacion': 'Verify recovery code',
'restaurar_contrasena': 'Reset Password',
'escribir_nueva_contrasena': 'Enter new password',
'nueva_contrasena': 'New password',
'confirmar_nueva_contrasena': 'Confirm new password',
'continuar': 'Continue',
};

final Map<String, String> portugues = {

  'haz_click_aqui': 'Clique aqui!',
  'tu_proxima_gran_idea': 'Sua próxima grande ideia começa aqui!💫',
  'mensaje_inicio':
      'Crie sua conta em 30 segundos e descubra tudo o que temos para você',
'comenzar': 'Começar agora',
  'iniciar_sesion': 'Entrar',
  'iniciar_sesion_titulo': 'Entrar',
  'crear_cuenta': 'Criar conta',
  'correo': 'E-mail',
  'correo_electronico': 'E-mail',
  'contrasena': 'Senha',
  'confirmar_contrasena': 'Confirmar senha',
  'olvidaste_contrasena': 'Esqueceu a senha?',
  'nombre': 'Nome',
  'telefono': 'Telefone',
  'recordarme': 'Lembrar de mim',
  'no_tienes_cuenta': 'Não tem uma conta? Cadastre-se',
  'continuar_con': 'Ou continuar com',
  'historial': 'Histórico',
  'resenas': 'Avaliações',
  'menu': 'Menu',
  'perfil': 'Perfil',
  'mensajes': 'Mensagens',
  'cerrar_sesion': 'Sair',
  'registro': 'Cadastre-se',
'crear_cuenta_boton': 'Criar conta',
'error_contrasenas': 'As senhas não coincidem',
'correo_registrado': 'Esse e-mail já está registrado',
'error_servidor': 'Não foi possível conectar ao servidor',
'verificando_correo': 'Verificando o E-mail',
'ingresa_codigo': 'Digite o código de verificação',
'verificar_proceder': 'Verificar e Continuar',
'reenviar_codigo': 'Reenviar código',
'codigo_incorrecto': 'Código incorreto',
'recuperar_contrasena': 'Recuperar Senha',
'no_se_pudo_enviar': 'Não foi possível enviar o código',
'verificar_codigo_recuperacion': 'Verificar o código de recuperação',
'restaurar_contrasena': 'Redefinir Senha',
'escribir_nueva_contrasena': 'Digite uma nova senha',
'nueva_contrasena': 'Nova senha',
'confirmar_nueva_contrasena': 'Confirmar nova senha',
'continuar': 'Continuar',
};